### ISSUE TITLE
Add variable in status message

### ISSUE THREAD

**Issue by straumat** [ethomson/send-tweet-action#3]
From my CI, I retrieve the project release with  `${{ steps.package.outputs.version }}`

I would like to make a tweet including the release number, how should i do it ? 

status: "Tading bot ${{ steps.package.outputs.version }} released - more information here : https://github.com/cassandre-tech/cassandre-trading-bot/releases"
?

Thanks a lot for your work

**Comment by ethomson** [comment]
Yes, that should work!  You could also get the URL to the release itself from the step that creates the release.  Something like:

```
- name : Publish the release announce on Twitter
   uses: ethomson/send-tweet-action@v1
   with:
     status: "Trading bot ${{ steps.package.outputs.version }} release - more information here : ${{ steps.create_release.outputs.html_url }}"
```

**Comment by straumat** [comment]
Thanks, I will make a test soon anc close if it's ok
