### ISSUE TITLE
Unable to use environment variables in status message

### ISSUE THREAD

**Issue by riprasad** [ethomson/send-tweet-action#7]
I want to use the environment variable some thing like this:-

```
- name : Publish the release announce on Twitter
   uses: ethomson/send-tweet-action@v1
   with:
     status: "Checkout our latest release : $VERSION"
```

**Comment by backspace** [comment]
Maybe there’s another way but you can do this via an environment variable, as I did [here](https://github.com/Real-Team-Manitoba/manitoba-covid-deaths/commit/419c10dcf443c99d01049d582eb6f526aaa68aad).

**Comment by ethomson** [comment]
Precisely, @backspace!  This is how you refer to environment variables in an action.  Thanks for the great example

**Comment by baruchiro** [comment]
Yes, but how can you create a long tweet? Do I need to run a pre-command to generate the whole tweet text and put it in EnvVar?

**Comment by backspace** [comment]
yes, that’s how I do it [here](https://github.com/Real-Team-Manitoba/manitoba-covid-deaths/blob/main/.github/workflows/scrape-and-post.yml#L31).
